import {
  AlertTriangle,
  ArrowRight,
  ArrowDown,
  ArrowUp,
  ArrowLeftRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  Users,
  X,
  Eye,
  EyeOff,
  Shield,
  Fingerprint,
  Filter,
  Download,
  RefreshCw,
  BarChart3,
  Database,
  Bell,
  Archive,
  Banknote,
  PiggyBank,
  Search,
  MessageCircle,
  Mail,
  Phone,
  TrendingUp,
  Home,
  Receipt,
  Menu,
  LogOut,
} from "lucide-react"

export type Icon = LucideProps

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  Eye: Eye,
  EyeOff: EyeOff,
  Shield: Shield,
  Fingerprint: Fingerprint,
  User: User,
  Users: Users,
  Loader2: Loader2,
  CreditCard: CreditCard,
  ArrowRight: ArrowRight,
  ArrowDown: ArrowDown,
  ArrowUp: ArrowUp,
  ArrowLeftRight: ArrowLeftRight,
  Filter: Filter,
  Plus: Plus,
  Settings: Settings,
  AlertTriangle: AlertTriangle,
  Bell: Bell,
  Archive: Archive,
  RefreshCw: RefreshCw,
  Check: Check,
  Download: Download,
  FileText: FileText,
  BarChart3: BarChart3,
  Database: Database,
  Banknote: Banknote,
  PiggyBank: PiggyBank,
  Search: Search,
  MessageCircle: MessageCircle,
  Mail: Mail,
  Phone: Phone,
  TrendingUp: TrendingUp,
  Home: Home,
  Receipt: Receipt,
  HelpCircle: HelpCircle,
  Menu: Menu,
  X: X,
  LogOut: LogOut,
}